---
deployment:
  tasks:
    - export DEPLOYPATH=/home/obfuzbhr/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R forms $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp category.html $DEPLOYPATH
    - /bin/cp changelog.txt $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp Readme.txt $DEPLOYPATH
    - /bin/cp searchResult.html $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp singlePost.html $DEPLOYPATH